#!/bin/bash
set -e

# Apache gets grumpy about PID files pre-existing
rm -f /var/run/apache2/apache2.pid

# sed -i "s/AllowOverride None/AllowOverride All/g" /etc/apache2/apache2.conf
a2enmod rewrite


if [ -n "${XDEBUG_HOST}" ]; then
  sed -i "s/.*remote_host.*/xdebug.remote_host=${XDEBUG_HOST}/" /usr/local/etc/php/php.ini
fi
if [ -n "${XDEBUG_PORT}" ]; then
  sed -i "s/.*remote_port.*/xdebug.remote_port=${XDEBUG_PORT}/" /usr/local/etc/php/php.ini
fi
exec apache2 -DFOREGROUND
